добавил в бекенд HEALTHCHECK через компос

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -2,6 +2,9 @@ FROM python:3.9-slim
 #add user
 RUN groupadd -r efmobile && useradd -r -g efmobile efmobileuser
 
+# Установка curl для healthcheck
+RUN apt-get update && apt-get install -y curl
+
 COPY app.py /app/app.py
 
 WORKDIR /app
@@ -10,7 +13,7 @@ USER efmobileuser
 
 EXPOSE 8080
 
-HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
-  CMD curl -f http://localhost:8080/health || exit 1
+#HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
+#  CMD curl -f http://localhost:8080 || exit 1
 
 CMD ["python", "app.py", "--host", "0.0.0.0", "--port", "8080"]
